### ISSUE TITLE
Not able to test soukai bookmark app

### ISSUE THREAD

**Issue by thhck** [solid-contrib/data-modules#52]
Quickly going through the [readme](https://github.com/solid-contrib/data-modules/tree/main/bookmarks/soukai) of the soukai bookmark app. 
After running 
```
git clone https://github.com/solid-contrib/data-modules
cd data-modules
cd bookmarks/soukai
npm install
npm run test
```

I got 
```

> soukai-solid-bookmarks@0.0.0 test
> jest

 FAIL  test/Bookmark.test.ts
  ● Test suite failed to run

    /home/user/liquid/data-modules/bookmarks/soukai/node_modules/node-fetch/src/utils/form-data.js:1
    ReferenceError: Buffer is not defined

      at Object.<anonymous> (node_modules/node-fetch/src/utils/form-data.js:7:24)
      at Object.require.extensions.<computed> (node_modules/ts-node/src/index.ts:1608:43)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.295 s
Ran all test suites.
```

( Edit: tested with node v. 18.16.1 )

**Comment by soltanireza65** [comment]
@thhck 
<img width="356" alt="Screenshot 2023-12-12 at 12 32 02 PM" src="https://github.com/solid-contrib/data-modules/assets/53468377/9524d759-1d06-496d-b2c6-989de4fd76d3">

This is what I'm getting while I'm running `npm test` in `bookmarks/soukai`

**Comment by thhck** [comment]
Which node and npm version do you use?

**Comment by soltanireza65** [comment]
npm --version === 10.2.3
node --version === 20.10.0

**Comment by thhck** [comment]
Ok its working now. 
The first bug was using node v. 18, I also tested with v. 21 and got a different error:
```
> soukai-solid-bookmarks@0.0.0 test
> jest

 FAIL  test/Bookmark.test.ts
  ● Test suite failed to run

    TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function

      at $o (node_modules/esm/esm.js:1:224377)
      at wu (node_modules/esm/esm.js:1:227324)
      at Eu (node_modules/esm/esm.js:1:227999)
      at Object.<anonymous> (node_modules/esm/esm.js:1:295976)
      at n (node_modules/esm/esm.js:1:279589)
      at Object.<anonymous> (node_modules/@digitalbazaar/http-client/index.js:8:18)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.183 s, estimated 6 s
Ran all test suites.
(node:175174) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by soltanireza65** [comment]
I would pin the node and NPM versions

**Comment by soltanireza65** [comment]
fixed by https://github.com/solid-contrib/data-modules/pull/54
